export const GET_EMPLOYEES_SUCCEEDED = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILED = 'GET_EMPLOYEES_FAILED';
export const GET_EMPLOYEES_LOADING = 'GET_EMPLOYEES_LOADING';
export const CHECK_EMPLOYEE = 'CHECK_EMPLOYEE';
export const UNCHECK_EMPLOYEE = 'UNCHECK_EMPLOYEE';
export const CLEAR_SELECTED = 'CLEAR_SELECTED';
